import {
    ARCANE_MONSTERS,
    ArcaneMonsterPoint,
    ArcanePoint
} from './ArcaneWarriorLevelConfig';

export interface ArcaneTreasureLevelConfig {
    treasure_level_id: string;
    level_no: number;
    name: string;
    map_width_grid: number;
    map_height_grid: number;
    cell_size_px: number;
    analysis_limit_count: number;
    start_point: ArcanePoint;
    monster_points: ArcaneMonsterPoint[];
    blocked_points: ArcanePoint[];
}

const CHAPTER_NAMES = ['秘库初启', '铜钟藏室', '裂隙宝廊', '星界密藏', '永夜宝库'];
const STAGE_NAMES = [
    '微光', '石语', '回声', '旧印', '暗门',
    '残页', '环厅', '断桥', '迷阵', '冷焰',
    '密钥', '镜廊', '钟摆', '星痕', '藏锋',
    '错层', '深潜', '封锁', '终试', '镇守'
];

// Generated by the offline reachability solver for the fixed layouts below.
// Each value is the length of one valid analysis route for that level.
const OFFLINE_SOLVER_ROUTE_LENGTHS = [
    5, 8, 6, 6, 5, 5, 4, 5, 6, 6, 5, 5, 6, 6, 5, 7, 6, 7, 6, 6,
    8, 7, 6, 7, 6, 6, 7, 9, 7, 8, 6, 5, 8, 6, 6, 6, 6, 8, 9, 9,
    9, 7, 7, 9, 6, 6, 6, 6, 8, 7, 8, 9, 10, 8, 8, 9, 9, 9, 9, 8,
    10, 8, 10, 10, 11, 9, 10, 10, 11, 11, 10, 7, 11, 10, 11, 12, 9, 12, 11, 12,
    12, 10, 11, 10, 15, 9, 11, 10, 12, 8, 11, 12, 12, 9, 11, 14, 12, 11, 12, 10
];

// Valid routes generated with the largest selectable hero footprint (3x3).
const OFFLINE_SOLVER_ROUTE_LENGTHS_BODY_3 = [
    9, 13, 10, 11, 9, 8, 7, 8, 11, 11, 9, 9, 10, 10, 8, 11, 10, 12, 9, 11,
    12, 11, 10, 12, 11, 11, 13, 16, 12, 14, 11, 8, 13, 10, 10, 11, 11, 14, 12, 14,
    17, 12, 13, 13, 11, 11, 11, 10, 12, 10, 13, 13, 17, 14, 14, 14, 15, 16, 14, 14,
    15, 16, 21, 14, 21, 14, 17, 17, 16, 16, 19, 14, 20, 20, 19, 21, 20, 24, 20, 20,
    24, 17, 22, 20, 25, 13, 20, 17, 24, 12, 18, 19, 21, 16, 20, 22, 21, 21, 17, 16
];

function getAnalysisLimit(levelNo: number): number {
    let required = 0;
    for (let index = 0; index < levelNo; index++) {
        required = Math.max(required, OFFLINE_SOLVER_ROUTE_LENGTHS_BODY_3[index]);
    }
    return required + 2;
}

function keyOf(x: number, y: number): string {
    return x + ',' + y;
}

function padLevel(levelNo: number): string {
    return ('000' + levelNo).slice(-3);
}

function createFixedRandom(seed: number): () => number {
    let state = seed >>> 0;
    return () => {
        state = (state * 1664525 + 1013904223) >>> 0;
        return state / 4294967296;
    };
}

function buildBlockedPoints(levelNo: number, width: number, height: number): ArcanePoint[] {
    const chapter = Math.floor((levelNo - 1) / 20);
    const blocked: ArcanePoint[] = [];
    const occupied: { [key: string]: boolean } = {};
    const islandCount = chapter + Math.floor(((levelNo - 1) % 20) / 7);

    for (let island = 0; island < islandCount; island++) {
        const baseX = 12 + ((levelNo * 5 + island * 9) % Math.max(4, width - 18));
        const baseY = 5 + ((levelNo * 3 + island * 7) % Math.max(4, height - 10));
        const islandSize = island % 3 === 2 ? 3 : 2;
        for (let y = 0; y < islandSize; y++) {
            for (let x = 0; x < islandSize; x++) {
                const px = baseX + x;
                const py = baseY + y;
                if (px >= width - 3 || py >= height - 3) continue;
                const key = keyOf(px, py);
                if (!occupied[key]) {
                    occupied[key] = true;
                    blocked.push({ x: px, y: py });
                }
            }
        }
    }
    return blocked;
}

function canPlaceMonster(
    x: number,
    y: number,
    size: number,
    width: number,
    height: number,
    blocked: { [key: string]: boolean },
    occupied: { [key: string]: boolean }
): boolean {
    if (x < 4 || y < 3 || x + size >= width - 2 || y + size >= height - 2) return false;
    for (let oy = 0; oy < size; oy++) {
        for (let ox = 0; ox < size; ox++) {
            const key = keyOf(x + ox, y + oy);
            if (blocked[key] || occupied[key]) return false;
        }
    }
    return true;
}

function buildMonsterPoints(
    levelNo: number,
    width: number,
    height: number,
    blockedPoints: ArcanePoint[]
): ArcaneMonsterPoint[] {
    const chapter = Math.floor((levelNo - 1) / 20);
    const stage = (levelNo - 1) % 20;
    const availableTypes = Math.min(5, 1 + chapter + (stage >= 10 ? 1 : 0));
    const targetCount = Math.min(8, 2 + Math.floor((levelNo - 1) / 12));
    const searchMaxX = Math.min(width - 3, 14 + chapter + Math.floor(stage / 12));
    const searchMaxY = Math.min(height - 3, 10 + chapter + Math.floor(stage / 15));
    const random = createFixedRandom(0x73a9c51d ^ (levelNo * 2246822519));
    const blocked: { [key: string]: boolean } = {};
    const occupied: { [key: string]: boolean } = {};
    const points: ArcaneMonsterPoint[] = [];
    blockedPoints.forEach((point) => { blocked[keyOf(point.x, point.y)] = true; });

    let attempts = 0;
    while (points.length < targetCount && attempts < 4000) {
        attempts++;
        const monsterIndex = (levelNo + points.length + Math.floor(random() * availableTypes)) % availableTypes;
        const monster = ARCANE_MONSTERS[monsterIndex];
        const size = monster.body_size_grid;
        const maxAnchorX = Math.max(5, searchMaxX - size + 1);
        const maxAnchorY = Math.max(3, searchMaxY - size + 1);
        const x = 5 + Math.floor(random() * Math.max(1, maxAnchorX - 4));
        const y = 3 + Math.floor(random() * Math.max(1, maxAnchorY - 2));
        if (!canPlaceMonster(x, y, size, width, height, blocked, occupied)) continue;

        points.push({ x, y, monster_id: monster.entity_id });
        for (let oy = -1; oy <= size; oy++) {
            for (let ox = -1; ox <= size; ox++) occupied[keyOf(x + ox, y + oy)] = true;
        }
    }

    if (points.length !== targetCount) {
        throw new Error('T' + padLevel(levelNo) + ' monster layout generation failed');
    }
    return points;
}

function buildLevel(levelNo: number): ArcaneTreasureLevelConfig {
    const chapter = Math.floor((levelNo - 1) / 20);
    const stage = (levelNo - 1) % 20;
    const width = 30 + chapter * 2 + Math.floor(stage / 10);
    const height = 20 + chapter * 2;
    const blockedPoints = buildBlockedPoints(levelNo, width, height);
    const monsterPoints = buildMonsterPoints(levelNo, width, height, blockedPoints);
    const analysisLimit = getAnalysisLimit(levelNo);

    return {
        treasure_level_id: 'T' + padLevel(levelNo),
        level_no: levelNo,
        name: CHAPTER_NAMES[chapter] + '·' + STAGE_NAMES[stage],
        map_width_grid: width,
        map_height_grid: height,
        cell_size_px: 32,
        analysis_limit_count: analysisLimit,
        start_point: { x: 2, y: 2 },
        monster_points: monsterPoints,
        blocked_points: blockedPoints
    };
}

function validateLevel(level: ArcaneTreasureLevelConfig): void {
    const blocked: { [key: string]: boolean } = {};
    const occupied: { [key: string]: boolean } = {};
    level.blocked_points.forEach((point) => { blocked[keyOf(point.x, point.y)] = true; });
    if (blocked[keyOf(level.start_point.x, level.start_point.y)]) {
        throw new Error(level.treasure_level_id + ' blocks its start point');
    }
    if (level.analysis_limit_count <= 0 || level.monster_points.length <= 0) {
        throw new Error(level.treasure_level_id + ' has invalid treasure goals');
    }
    if (level.analysis_limit_count < OFFLINE_SOLVER_ROUTE_LENGTHS[level.level_no - 1]
        || level.analysis_limit_count < OFFLINE_SOLVER_ROUTE_LENGTHS_BODY_3[level.level_no - 1]) {
        throw new Error(level.treasure_level_id + ' does not satisfy its offline solver route');
    }
    level.monster_points.forEach((point) => {
        const monster = ARCANE_MONSTERS.filter((item) => item.entity_id === point.monster_id)[0];
        if (!monster) throw new Error(level.treasure_level_id + ' references an unknown monster');
        for (let oy = 0; oy < monster.body_size_grid; oy++) {
            for (let ox = 0; ox < monster.body_size_grid; ox++) {
                const x = point.x + ox;
                const y = point.y + oy;
                const key = keyOf(x, y);
                if (x < 0 || y < 0 || x >= level.map_width_grid || y >= level.map_height_grid
                    || blocked[key] || occupied[key]) {
                    throw new Error(level.treasure_level_id + ' has an overlapping monster footprint');
                }
                occupied[key] = true;
            }
        }
    });
}

export const ARCANE_TREASURE_LEVELS: ArcaneTreasureLevelConfig[] = [];
for (let levelNo = 1; levelNo <= 100; levelNo++) {
    const level = buildLevel(levelNo);
    validateLevel(level);
    ARCANE_TREASURE_LEVELS.push(level);
}

export function getArcaneTreasureLevel(levelNo: number): ArcaneTreasureLevelConfig {
    const index = Math.max(0, Math.min(ARCANE_TREASURE_LEVELS.length - 1, Math.floor(levelNo || 1) - 1));
    return ARCANE_TREASURE_LEVELS[index];
}
